<?php
// routes/web.php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Route;

/**
 * Web Routes
 *
 * All routes below are protected by the 'auth' middleware,
 * meaning unauthenticated users are redirected to /login.
 *
 * Route::resource() automatically registers all 7 RESTful routes:
 *   companies.index    GET    /companies
 *   companies.create   GET    /companies/create
 *   companies.store    POST   /companies
 *   companies.show     GET    /companies/{company}
 *   companies.edit     GET    /companies/{company}/edit
 *   companies.update   PUT    /companies/{company}
 *   companies.destroy  DELETE /companies/{company}
 */

// Redirect root to companies list
Route::get('/', function () {
    return redirect()->route('companies.index');
});

// Protected routes — user must be logged in
Route::middleware(['auth', 'verified'])->group(function () {
    Route::resource('companies', CompanyController::class);
    Route::resource('employees', EmployeeController::class);
});

// Auth routes (login, logout) — provided by Laravel Breeze
// This file is auto-generated by `php artisan breeze:install`
require __DIR__ . '/auth.php';
